module.exports = {
  api: null,
  service: null,
  port: null,
  host: null,
  clustered: false,
  shouldNotPrefetch: [],
  shouldNotPreload: [],
  entry: target => `./src/entry-${target}`,
  defaultTitle: 'My app',
  favicon: './public/favicon.ico',
  skipRequests: req => req.originalUrl === '/graphql',
  nodeExternalsWhitelist: [/\.css$/, /\?vue&type=style/],
  applyDefaultServer: true,
  extendServer: null,
  staticCacheTtl: 1000 * 60 * 60 * 24 * 30,
  directives: {},
  lruCacheOptions: {},
  onRender: null,
  onError: null,
  // Paths
  distPath: null,
  error500Html: null,
  templatePath: null,
  serviceWorkerPath: null,
}
